package domain

val TEAM_MEMBERS: Int = 5
val COMPETITOR_RESISTANCE_MEAN: Int = 35
val COMPETITOR_RESISTANCE_DESV: Int = 10
val COMPETITOR_EXPERIENCE: Int = 10
val COMPETITOR_MIN_LUCK: Float = 1
val COMPETITOR_MAX_LUCK: Float = 3
val SHOOT_RESISTANCE_COST: Int = 5
val SCORE_FOR_WIN_ROUND: Int = 3
