package domain

val TEAM_MEMBERS:Int = 5
val COMPETITOR_RESISTANCE:Int = 35
val COMPETITOR_RESISTANCE_VARIABLE:Int = 10
val COMPETITOR_EXPERIENCE:Int = 10
val COMPETITOR_MIN_LUCK: Float = 1
val COMPETITOR_MAX_LUCK: Float = 3
val SHORT_RESISTANCE_COST: Int = 5
